### ISSUE TITLE
Android sample crashes on start up

### ISSUE THREAD

**Issue by shodanuk** [Wikitude/wikitude-titanium#34]
Hi there,

I'm trying to run the Android sample on device but it's crashing as soon as it starts with the following error:

```
[ERROR] art: dlopen("/data/app/com.wikitude.titaniumsample-1/lib/arm/libcom.wikitude.ti.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__exidx_end" referenced by "libcom.wikitude.ti.so"...
[ERROR] TiApplication: (KrollRuntimeThread) [40,162] Sending event: exception on thread: KrollRuntimeThread msg:java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__exidx_end" referenced by "libcom.wikitude.ti.so"...; Titanium 3.5.1,2015/03/05 10:08,96875c9
[ERROR] TiApplication: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__exidx_end" referenced by "libcom.wikitude.ti.so"...
[ERROR] TiApplication: 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
[ERROR] TiApplication: 	at java.lang.System.loadLibrary(System.java:989)
[ERROR] TiApplication:
[ERROR] TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
[ERROR] TiApplication: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:185)
[ERROR] TiApplication: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)
[ERROR] AndroidRuntime: FATAL EXCEPTION: KrollRuntimeThread
[ERROR] AndroidRuntime: Process: com.wikitude.titaniumsample, PID: 11982
[ERROR] AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__exidx_end" referenced by "libcom.wikitude.ti.so"...
[ERROR] AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
[ERROR] AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:989)
[ERROR] AndroidRuntime: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
[ERROR] AndroidRuntime: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
[ERROR] AndroidRuntime: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:185)
[ERROR] AndroidRuntime: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)
```

I can confirm that I've installed the com.wikitude.ti android module into ```/modules``` directory of my project. I can see the file mentioned in the error message above in ```/modules/android/com.wikitude.ti/4.1.0/libs/armeabi``` and in ```armeabi-v7a``` and ```x86``` directories aswell.

My environment is as follows:

* OSX 10.10
* Wikitude SDK 4.1.0
* Ti SDK 3.5.0.GA
* Ti CLI 4.1.0
* Samsung Galaxy S5 running Android 5.0

**Comment by shodanuk** [comment]
Just double checked and the noticed the required Ti SDK in tiapp.xml had been bumped to 3.5.1.GA. Have put it back to 3.5.0.GA and now the app works.

Any plans to support >3.5.0.GA ? It's getting pretty old now and Android particularly has benefitted from from recent Ti SDK releases.

**Comment by AndreasSchacherbauerWikitude** [comment]
Our latest release from July 11, 2016 should again work with the latest version of the Ti SDK.
